// Data Science Interactive Workbench & Activity Suite with Target Container Support & Safe Event Handling

const sampleSurveyData = [
    { id: 1, age_group: '30-44', edu: 'Master', ai_risk: 4, tech_fam: 5, ai_trust: 1, weight: 1.25 },
    { id: 2, age_group: '18-29', edu: 'Bachelor', ai_risk: 2, tech_fam: 4, ai_trust: 1, weight: 0.95 },
    { id: 3, age_group: '45-59', edu: 'High School', ai_risk: 5, tech_fam: 2, ai_trust: 0, weight: 1.10 },
    { id: 4, age_group: '60+', edu: 'PhD', ai_risk: 4, tech_fam: 3, ai_trust: 0, weight: 1.40 },
    { id: 5, age_group: '18-29', edu: 'Master', ai_risk: 1, tech_fam: 5, ai_trust: 1, weight: 0.88 },
    { id: 6, age_group: '30-44', edu: 'Bachelor', ai_risk: 3, tech_fam: 3, ai_trust: 0, weight: 1.05 },
    { id: 7, age_group: '45-59', edu: 'Master', ai_risk: 4, tech_fam: 4, ai_trust: 0, weight: 1.15 },
    { id: 8, age_group: '18-29', edu: 'High School', ai_risk: 2, tech_fam: 4, ai_trust: 1, weight: 0.92 },
    { id: 9, age_group: '60+', edu: 'Bachelor', ai_risk: 5, tech_fam: 1, ai_trust: 0, weight: 1.35 },
    { id: 10, age_group: '30-44', edu: 'PhD', ai_risk: 2, tech_fam: 5, ai_trust: 1, weight: 1.00 }
];

let activeDsTab = 'feature_engineering';

function renderDsActivitySuite(tabKey, targetContainerId, evt) {
    activeDsTab = tabKey || 'feature_engineering';
    
    // Support stage-specific containers: dsStage1, dsStage2, dsStage3, or default dsStage
    const targetId = targetContainerId || (activeDsTab === 'feature_engineering' ? 'dsStage1' : activeDsTab === 'ml_comparison' ? 'dsStage2' : 'dsStage3');
    const stage = document.getElementById(targetId) || document.getElementById('dsStage1') || document.getElementById('dsStage');
    if (!stage) return;

    document.querySelectorAll('.ds-tab-btn').forEach(b => b.classList.remove('active'));
    
    const target = (evt && evt.currentTarget) ? evt.currentTarget : (typeof window !== 'undefined' && window.event && window.event.target ? window.event.target : null);
    if (target && target.classList) {
        target.classList.add('active');
    }

    if (activeDsTab === 'guide') {
        stage.innerHTML = `
            <div>
                <h3 style="color: var(--gold-primary); font-family: var(--font-heading); margin-bottom: 8px;">📋 Step-by-Step Data Guide & Dictionary</h3>
                <p style="color: var(--text-main); font-size: 1rem; line-height: 1.6; margin-bottom: 20px; background: rgba(255,199,44,0.08); padding: 16px; border-radius: 12px; border-left: 4px solid var(--gold-primary);">
                    <strong>What dataset is this?</strong> A <strong>synthetic</strong> survey dataset of 1,200 simulated respondents, generated by
                    <code>scripts/setup_ai_trust_data.py</code> (seed 42) and modeled on the public Kaggle <em>AI Trust Insights</em> dataset (CC0).
                    Each row represents <strong>one simulated respondent</strong> with age, education, perceived AI risk, and trust in AI technology.
                    Because the generating process is known, education and tech familiarity genuinely drive trust &mdash; while age and gender are deliberately noise.
                </p>

                <!-- Data Dictionary Table — rendered from js/dataset_config.js.
                     A hardcoded copy used to live here and silently drifted out of sync
                     with the generator (stale IDs, wrong age bracket, 10 missing columns).
                     Keep ONE source of truth. -->
                <div id="dsGuideDictionary" style="background: rgba(0,0,0,0.5); border: 1px solid rgba(255,255,255,0.15); border-radius: 14px; overflow-x: auto; margin-bottom: 20px;"></div>

                <div style="text-align: center;">
                    <button class="fb-action-btn gold" onclick="renderDsActivitySuite('feature_engineering', '${targetId}')">Start Activity 1: Feature Engineering Lab ➔</button>
                </div>
            </div>
        `;
        // Populate the dictionary from the single source of truth.
        if (typeof renderDataDictionary === 'function') renderDataDictionary('dsGuideDictionary');
    } else if (activeDsTab === 'feature_engineering') {
        stage.innerHTML = `
            <div>
                <div style="background: rgba(6, 182, 212, 0.1); border-left: 4px solid var(--cyan-magic); padding: 14px; border-radius: 8px; margin-bottom: 20px;">
                    <strong style="color: var(--cyan-magic);">🎯 What We Are Trying To Do:</strong> We take raw survey answers (containing <code>-9</code> missing codes and Likert 1-5 scales) and clean them into binary 1/0 indicator flags.<br>
                    <strong style="color: var(--gold-primary);">❓ Why We Do It:</strong> Machine learning algorithms and SAS PROC LOGISTIC need clean 1/0 indicator columns to fit regression equations!
                </div>

                <h3 style="color: var(--gold-primary); font-family: var(--font-heading); margin-bottom: 8px;">📊 Activity 1: Survey Feature Engineering & Imputation Lab</h3>

                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px;">
                    <!-- Recode Controls -->
                    <div style="background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 16px; padding: 20px;">
                        <h4 style="color: var(--accent-blue); font-size: 1rem; margin-bottom: 12px;">1. Select Likert Recode Threshold:</h4>
                        <div class="sandbox-input-group">
                            <label class="sandbox-label">Flag 'High Risk' if Perceived AI Risk >=</label>
                            <select id="recodeCutoff" class="sandbox-select" onchange="runFeatureRecode()">
                                <option value="3">>= 3 (Moderate + High)</option>
                                <option value="4" selected>>= 4 (High Risk Only)</option>
                                <option value="5">>= 5 (Extreme Risk Only)</option>
                            </select>
                        </div>

                        <div class="sandbox-input-group">
                            <label class="sandbox-label">Missing Value (-9) Imputation Strategy:</label>
                            <select id="imputeStrategy" class="sandbox-select" onchange="runFeatureRecode()">
                                <option value="none">SAS Style: Convert -9 to None / NaN</option>
                                <option value="median">Data Science Style: Impute with Column Median</option>
                                <option value="drop">Drop Rows with Missing Values</option>
                            </select>
                        </div>
                    </div>

                    <!-- Live Calculated Summary -->
                    <div style="background: rgba(18, 24, 38, 0.8); border: 1px solid var(--gold-primary); border-radius: 16px; padding: 20px;">
                        <h4 style="color: var(--gold-primary); font-size: 1rem; margin-bottom: 12px;">📈 Calculated Survey Statistics:</h4>
                        <div id="recodeStatsOutput" style="font-family: var(--font-mono); font-size: 0.9rem; color: #4ADE80;">
                            Calculating feature engineering outputs...
                        </div>
                    </div>
                </div>

                <div style="background: rgba(0,0,0,0.5); border-radius: 12px; padding: 16px; font-family: var(--font-mono); font-size: 0.85rem; color: #38BDF8;" id="recodeCodeSnippet">
                    # Python Pandas Recoding Code generated automatically!
                </div>
            </div>
        `;
        runFeatureRecode();
    } else if (activeDsTab === 'ml_comparison') {
        stage.innerHTML = `
            <div>
                <div style="background: rgba(139, 92, 246, 0.15); border-left: 4px solid var(--purple-primary); padding: 14px; border-radius: 8px; margin-bottom: 20px;">
                    <strong style="color: var(--purple-glow);">🎯 What We Are Trying To Do:</strong> We fit 3 different models to predict whether a respondent trusts AI (<code>High_AI_Trust = 1</code>) based on their age, education, and risk perception.<br>
                    <strong style="color: var(--gold-primary);">❓ Why We Do It:</strong> We want to compare traditional SAS PROC LOGISTIC (p-values & regression odds ratios) against modern Machine Learning (Random Forests) and cutting-edge Google TabFM (Zero-Shot Tabular Transformers)!
                </div>

                <h3 style="color: var(--gold-primary); font-family: var(--font-heading); margin-bottom: 8px;">🤖 Activity 2: Supervised ML Model Comparison Lab</h3>

                <!-- Model Tuning Controls -->
                <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px; margin-bottom: 20px;">
                    <div style="background: rgba(255,255,255,0.03); padding: 16px; border-radius: 12px; border: 1px solid rgba(255,255,255,0.1);">
                        <label class="sandbox-label">Train / Test Split Ratio:</label>
                        <select id="splitRatio" class="sandbox-select" onchange="runMlModelBenchmark()">
                            <option value="0.8" selected>80% Train / 20% Test</option>
                            <option value="0.7">70% Train / 30% Test</option>
                            <option value="0.5">50% Train / 50% Test</option>
                        </select>
                    </div>

                    <div style="background: rgba(255,255,255,0.03); padding: 16px; border-radius: 12px; border: 1px solid rgba(255,255,255,0.1);">
                        <label class="sandbox-label">Random Forest Trees (n_estimators):</label>
                        <select id="rfTrees" class="sandbox-select" onchange="runMlModelBenchmark()">
                            <option value="50">50 Trees</option>
                            <option value="100" selected>100 Trees</option>
                            <option value="200">200 Trees</option>
                        </select>
                    </div>

                    <div style="background: rgba(255,255,255,0.03); padding: 16px; border-radius: 12px; border: 1px solid rgba(255,255,255,0.1);">
                        <label class="sandbox-label">TabFM In-Context Memory Rows:</label>
                        <select id="tabfmRows" class="sandbox-select" onchange="runMlModelBenchmark()">
                            <option value="64">64 In-Context Rows</option>
                            <option value="128" selected>128 In-Context Rows</option>
                            <option value="256">256 In-Context Rows</option>
                        </select>
                    </div>
                </div>

                <!-- Model Performance Comparison Grid -->
                <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 20px; margin-bottom: 20px;">
                    
                    <!-- Logistic Regression -->
                    <div style="background: rgba(15, 23, 42, 0.9); border: 2px solid var(--accent-blue); border-radius: 16px; padding: 20px;">
                        <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:12px;">
                            <h4 style="color: var(--accent-blue); font-size:1.1rem; margin:0;">1. Logistic Regression</h4>
                            <span class="nb-badge" style="font-size:0.75rem;">SAS PROC LOGISTIC</span>
                        </div>
                        <div id="logisticStats" style="font-family: var(--font-mono); font-size:0.88rem; color:#FFF;">Calculating...</div>
                    </div>

                    <!-- Random Forest -->
                    <div style="background: rgba(15, 23, 42, 0.9); border: 2px solid var(--accent-purple); border-radius: 16px; padding: 20px;">
                        <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:12px;">
                            <h4 style="color: var(--accent-purple); font-size:1.1rem; margin:0;">2. Random Forest</h4>
                            <span class="nb-badge" style="font-size:0.75rem; background:rgba(139,92,246,0.2); color:var(--accent-purple);">Scikit-Learn</span>
                        </div>
                        <div id="rfStats" style="font-family: var(--font-mono); font-size:0.88rem; color:#FFF;">Calculating...</div>
                    </div>

                    <!-- Google TabFM Zero Shot -->
                    <div style="background: rgba(15, 23, 42, 0.9); border: 2px solid var(--gold-primary); border-radius: 16px; padding: 20px;">
                        <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:12px;">
                            <h4 style="color: var(--gold-primary); font-size:1.1rem; margin:0;">3. Google TabFM</h4>
                            <span class="nb-badge" style="font-size:0.75rem; background:rgba(255,199,44,0.2); color:var(--gold-primary);">Zero-Shot Transformer</span>
                        </div>
                        <div id="tabfmStats" style="font-family: var(--font-mono); font-size:0.88rem; color:#FFF;">Calculating...</div>
                    </div>
                </div>
            </div>
        `;
        runMlModelBenchmark();
    } else if (activeDsTab === 'hypothesis_testing') {
        stage.innerHTML = `
            <div>
                <div style="background: rgba(16, 185, 129, 0.15); border-left: 4px solid var(--green-hero); padding: 14px; border-radius: 8px; margin-bottom: 20px;">
                    <strong style="color: var(--green-hero);">🎯 What We Are Trying To Do:</strong> We test whether there is a statistically significant relationship between demographic variables (Age / Education) and High AI Trust.<br>
                    <strong style="color: var(--gold-primary);">❓ Why We Do It:</strong> Sociologists need Chi-Square ($\chi^2$) p-values and relative Odds Ratios to prove whether generational differences in AI trust are real or just random chance!
                </div>

                <h3 style="color: var(--gold-primary); font-family: var(--font-heading); margin-bottom: 8px;">🔬 Activity 3: Sociological Hypothesis & Crosstab Lab</h3>

                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px;">
                    <div style="background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 16px; padding: 20px;">
                        <h4 style="color: var(--accent-blue); font-size: 1rem; margin-bottom: 12px;">Select Survey Variables:</h4>
                        
                        <div class="sandbox-input-group">
                            <label class="sandbox-label">Row Variable (X Predictor):</label>
                            <select id="hypoRowVar" class="sandbox-select" aria-label="Row variable (X predictor)" onchange="runHypothesisTest()">
                                <option value="Age_Group" selected>Age Group</option>
                                <option value="Education_Level">Education Level</option>
                                <option value="Tech_Familiarity">Tech Familiarity</option>
                                <option value="Gender">Gender</option>
                            </select>
                        </div>

                        <div class="sandbox-input-group">
                            <label class="sandbox-label">Column Variable (Y Target):</label>
                            <select id="hypoColVar" class="sandbox-select" aria-label="Column variable (Y target)" onchange="runHypothesisTest()">
                                <option value="High_AI_Trust" selected>High AI Trust (1/0)</option>
                            </select>
                        </div>
                    </div>

                    <div style="background: rgba(18, 24, 38, 0.8); border: 1px solid var(--gold-primary); border-radius: 16px; padding: 20px;">
                        <h4 style="color: var(--gold-primary); font-size: 1rem; margin-bottom: 12px;">📊 Chi-Square & Crosstab Results:</h4>
                        <div id="hypoResultsOutput" style="font-family: var(--font-mono); font-size: 0.88rem; color: #4ADE80;">
                            Calculating statistics...
                        </div>
                    </div>
                </div>
            </div>
        `;
        runHypothesisTest();
    }
}

function runFeatureRecode() {
    const cutoffEl = document.getElementById('recodeCutoff');
    const imputeEl = document.getElementById('imputeStrategy');
    if (!cutoffEl || !imputeEl) return;

    const cutoff = parseInt(cutoffEl.value);
    const impute = imputeEl.value;
    const statsOut = document.getElementById('recodeStatsOutput');
    const codeOut = document.getElementById('recodeCodeSnippet');

    let processed = sampleSurveyData.map(d => ({ ...d }));

    if (impute === 'drop') {
        processed = processed.filter(d => d.ai_risk !== -9);
    } else if (impute === 'median') {
        processed = processed.map(d => ({ ...d, ai_risk: d.ai_risk === -9 ? 3 : d.ai_risk }));
    }

    // Rows still carrying the -9 missing code must be excluded from BOTH the
    // flag count and the weighted mean. Including them dragged the mean far
    // below the true value and contradicted the Python snippet shown below.
    const valid = processed.filter(d => d.ai_risk !== -9 && d.ai_risk !== null);
    const nMissing = processed.length - valid.length;

    const highRiskCount = valid.filter(d => d.ai_risk >= cutoff).length;
    const pct = valid.length ? Math.round((highRiskCount / valid.length) * 100) : 0;

    const totalWeight = valid.reduce((sum, d) => sum + d.weight, 0);
    const weightedRiskSum = valid.reduce((sum, d) => sum + (d.ai_risk * d.weight), 0);
    const weightedAvgRisk = totalWeight ? (weightedRiskSum / totalWeight).toFixed(2) : 'n/a';

    if (statsOut) {
        statsOut.innerHTML = `
            • Total Sample Rows Processed: <strong>${processed.length}</strong><br>
            • Excluded as missing (-9): <strong>${nMissing}</strong> → <strong>${valid.length}</strong> valid<br>
            • High Risk Flag Threshold: <strong>Perceived AI Risk >= ${cutoff}</strong><br>
            • High Risk Count: <strong>${highRiskCount} of ${valid.length} valid (${pct}%)</strong><br>
            • Population Weighted Mean Risk Score: <strong>${weightedAvgRisk} / 5.0</strong>
            <span style="color:var(--text-muted);">(missing excluded, as SAS does with <code>.</code>)</span>
        `;
    }

    if (codeOut) {
        codeOut.innerText = `# Python Pandas Equivalent Code:
df['AI_Risk_Clean'] = df['Perceived_AI_Risk'].replace(-9, ${impute === 'median' ? 'df["Perceived_AI_Risk"].median()' : 'None'})
df['High_Risk_Flag'] = (df['AI_Risk_Clean'] >= ${cutoff}).astype(int)
weighted_mean = (df['AI_Risk_Clean'] * df['Survey_Weight']).sum() / df['Survey_Weight'].sum()`;
    }
}

function runMlModelBenchmark() {
    const splitEl = document.getElementById('splitRatio');
    const treesEl = document.getElementById('rfTrees');
    const tabfmRowsEl = document.getElementById('tabfmRows');

    if (!splitEl || !treesEl || !tabfmRowsEl) return;

    const split = splitEl.value;
    const trees = treesEl.value;
    const tabfmRows = tabfmRowsEl.value;

    const logEl = document.getElementById('logisticStats');
    const rfEl = document.getElementById('rfStats');
    const tabfmEl = document.getElementById('tabfmStats');

    if (logEl) logEl.innerHTML = 'Fitting on the real dataset…';
    if (rfEl) rfEl.innerHTML = '…';
    if (tabfmEl) tabfmEl.innerHTML = '…';

    loadSurveyData().then(function (rows) {
        // A genuine fit on the real 1,200 rows. Changing the split ratio now
        // actually changes the numbers, because they are computed, not typed.
        const res = trainTestLogistic(
            rows,
            ['Education_Level', 'Tech_Familiarity', 'Age_Group'],
            ['Perceived_AI_Risk', 'Perceived_AI_Benefit'],
            'High_AI_Trust',
            parseFloat(split)
        );

        if (logEl) {
            logEl.innerHTML = `
                • Train/Test Split: ${Math.round(split * 100)}% / ${Math.round((1 - split) * 100)}%
                  (${res.nTrain} train, ${res.nTest} test)<br>
                • Test Accuracy: <strong>${(res.accuracy * 100).toFixed(1)}%</strong><br>
                • ROC-AUC Score: <strong>${res.auc.toFixed(3)}</strong><br>
                • <span style="color:var(--text-muted);">Computed live in your browser</span><br>
                • SAS Equivalent: <code>PROC LOGISTIC</code>
            `;
        }

        if (rfEl) {
            rfEl.innerHTML = `
                • Trees (n_estimators): ${trees}<br>
                • <span style="color:var(--text-muted);">A Random Forest is not implemented in this
                  in-page widget. Open <strong>Lab 02</strong> to fit one for real with
                  scikit-learn — the in-browser Python runtime has it.</span>
            `;
        }

        if (tabfmEl) {
            tabfmEl.innerHTML = `
                • In-Context Memory: ${tabfmRows} rows<br>
                • <span style="color:var(--text-muted);">TabFM cannot run in the browser — it needs
                  the <code>tabfm</code> package and pretrained weights. Figures from a Colab run
                  belong here; none are shown rather than invented.</span>
            `;
        }
    }).catch(function (err) {
        const msg = '<span style="color:#EF4444;">Could not load the dataset (' + err.message +
                    '). Serve over HTTP to compute these figures.</span>';
        if (logEl) logEl.innerHTML = msg;
        if (rfEl) rfEl.innerHTML = '';
        if (tabfmEl) tabfmEl.innerHTML = '';
    });
}

function runHypothesisTest() {
    const rowVarEl = document.getElementById('hypoRowVar');
    const colVarEl = document.getElementById('hypoColVar');
    const out = document.getElementById('hypoResultsOutput');

    if (!rowVarEl || !colVarEl || !out) return;

    const rowVar = rowVarEl.value;
    const colVar = colVarEl.value;

    out.innerHTML = 'Loading the full 1,200-row dataset…';

    loadSurveyData().then(function (rows) {
        const ct = crosstabChiSquare(rows, rowVar, colVar);
        const ors = oddsRatios(ct, 1);           // positive outcome = High_AI_Trust == 1
        const sig = ct.pValue < 0.05;

        // DATASET.signal records which predictors truly drive the outcome, so the
        // app can tell the learner whether their result matches ground truth.
        const isNoise = (typeof DATASET !== 'undefined') &&
                        DATASET.signal.noise.indexOf(rowVar) !== -1;

        const rowsHtml = ors.map(function (o) {
            return '• ' + o.level + ': ' + o.pct.toFixed(1) + '% High Trust ' +
                   '(n=' + o.n + ', OR ' +
                   (o.isReference ? '1.00 — reference' : o.oddsRatio.toFixed(2)) + ')';
        }).join('<br>');

        const verdict = sig
            ? '<span style="color:#4ADE80;">Statistically significant (p &lt; 0.05)</span>'
            : '<span style="color:#FBBF24;">Not statistically significant</span>';

        const truth = isNoise
            ? '<div style="margin-top:12px;padding:12px;background:rgba(251,191,36,0.1);' +
              'border-left:3px solid #FBBF24;border-radius:6px;color:var(--text-main);">' +
              '<strong>Ground truth:</strong> <code>' + rowVar + '</code> is <strong>pure noise</strong> ' +
              'in this dataset — it plays no part in the equation that generates trust ' +
              '(see <code>scripts/setup_ai_trust_data.py</code>). Finding no significant ' +
              'effect here is the <em>correct</em> result. Reporting a null finding with ' +
              'confidence is a real skill.</div>'
            : '<div style="margin-top:12px;padding:12px;background:rgba(74,222,128,0.1);' +
              'border-left:3px solid #4ADE80;border-radius:6px;color:var(--text-main);">' +
              '<strong>Ground truth:</strong> <code>' + rowVar + '</code> <strong>is</strong> ' +
              'one of the variables that genuinely drives trust in the generating equation. ' +
              'You just recovered a real effect from the data.</div>';

        const warn = ct.minExpected < 5
            ? '<br><em style="color:#FBBF24;">⚠️ Smallest expected cell count is ' +
              ct.minExpected.toFixed(1) + ' (&lt; 5) — chi-square may be unreliable here.</em>'
            : '';

        out.innerHTML =
            '<strong>Crosstab: ' + rowVar + ' × ' + colVar + '</strong> ' +
            '<span style="color:var(--text-muted);">(computed live, n = ' + ct.n + ')</span><br>' +
            rowsHtml + '<br><br>' +
            '<strong>Pearson Chi-Square:</strong> χ² = ' + ct.chi2.toFixed(2) +
            ' (df = ' + ct.df + ')<br>' +
            '<strong>p-value:</strong> ' + formatPValue(ct.pValue) + ' — ' + verdict + warn +
            '<br><br><em>SAS equivalent: PROC FREQ data=survey; tables ' +
            rowVar + '*' + colVar + ' / chisq relrisk; run;</em>' +
            truth;
    }).catch(function (err) {
        out.innerHTML =
            '<span style="color:#EF4444;">Could not load ' + SURVEY_CSV_PATH + ' — ' +
            err.message + '.<br>These statistics are computed from the real CSV, so they ' +
            'cannot be shown without it. Serve the app over HTTP ' +
            '(<code>python -m http.server 8000</code>) rather than opening the file directly.</span>';
    });
}

document.addEventListener('DOMContentLoaded', () => {
    renderDsActivitySuite('feature_engineering', 'dsStage1');
});
